external:
  kallisto: kallisto
  bowtie: bowtie

variantdb:
  ##num variants allowed
  var_limit: .na
  ##num cc lines allowed
  cc_limit: .na
  password: XXX
  chr_range: .na
  # - '16'
  # - '17'
  # - '18'
  # - '19'
  # - 'X'
  # - 'Y'
  # - 'MT'
  # - '1'
  # - '2'
  # - '3'
  # - '4'
  # - '5'
  # - '6'
  # - '7'
  # - '8'
  # - '9'
  # - '10'

  full:
    name: full_1410
    rebuildVCF: no
    rebuildFounder: no
    rebuildCC: no

  exon:
    name: exon_1410D
    rebuildVCF: yes
    rebuildFounder: yes
    rebuildCC: yes

  imprinted:
    name: imprinted_1410
    rebuildVCF: yes
    rebuildFounder: yes
    rebuildCC: yes

tmpdir: /data/doreper/tmp
data: /data/doreper/nd
output: /data/doreper/nd/output
