##Global props
##the root directory of all output
output: ../output

##the root directory of (almost) all data, with the exception of things that are too big to hold on
##local machines and in dropbox, such as rnaseq data
data: ../data

##
resources: /home/doreper/resources	

##The root directory of all temp files that are generated. This is in home
##because of horrible apparmor permissions issues; they can only be turned on for
##files without spaces, but my dropbox folder has spaces
tmpdir: ./tmp/

##Number of cores expected for certain parallelizable steps. Often overriden on cluster
mc.cores: 1.0

##whether we are running on the cluster or on local machine
onCluster: no


##properties related to genome of B6 model organism mouse
genome:
  ##DNA reference of b6, downloaded from ensembl
  dnaReferenceFile:  b6_reference/mus_musculus.GRCm38.75/genome.fa

  karyotype: b6_reference/mm10.chrom.sizes
  ##Feature file of b6, including exons, downloaded from ucsc
  exonReferenceFile: b6_reference/mus_musculus.GRCm38.75/Mus_musculus.GRCm38.75.gtf

  ##A file containing all the Andrew Morgan generated transcripts per founder, concatenated
  ##together. Originally intended for allignment of RNA-seq using callisto. Each transcript_id is unqique; the founder or set of founders specific to a particular transcript sequence is appended to the
  ##original transcript_id
  merged_transcriptome_apm: founder_reference/transcriptome_apm/joined.fa

  merged_alleles_apm: founder_reference/transcriptome_apm/joined.fa.allele

  ## A folder containing bowtie index information for the merged transcriptome of the 8 founders as asupplied by KB Choi
  merged_transcriptome_kb: founder_reference/merged_transcriptome_bwt_kwangbom

  ##The biomart host corresponding to the dna reference version (e.g. the release corresponding to 38.75). Needed for, among other things, pulling out up to date gene boundaries and gene symbols
  biomartHostForDNAReference: feb2014.archive.ensembl.org

  ##The vcf release that the genome assumes ... currently unused
  vcfRelease: '1410'

  ##A mapping file from old founder names to current (1410) founder names 
  foundersMap: cc_founderNameMap1410.txt

  ##A mapping file from the old style strain names to the new cc* style strain names
  ccNameMap:  cc_strainNameMap.csv

  ##The VCF file filtered by vcftools to only include the CC founders. 
  ##vcfDir: vcf/rel1410/filteredfounder
  vcfDir: vcf/rel1410/

  ## should the imprinted transcripts file be recomputed, or just use the one that was last written to file
  rebuildImprintedTrancriptsFile: no
  
  ##Should all exons be loaded and stored in memory? They are big.
  loadexons: no

  ##data of CC haplotype probabilities. Relative to data
  rilHaplotypeProbsDir: cc_probs_2016-03_mm10/

  ##A data file describing the imprinted and expressed genes found in the Crowley paper.
  ## needed to generate the imprinted genes list. Some fields may be defunct, and they are re
  ##replaced by biomart annotations
  imprintCrowleyExperimentFile: imprinted_genes_list/crowley_2015_brain_imprinted_genes.csv

  ##A data file describing the set of all mousebook genes, imprinted anywhere. Needed
  ## to generate the imprinted genes list
  ##Some fields may be defunct, and they are replaced by biomart annotations
  imprintLitFile: imprinted_genes_list/Literature_Imprinted_Genes.csv

  ##Data file describing snord115 locations
  ##Needed to generate the imprinted genes list
  snord115.file:  imprinted_genes_list/snord115_ensembl_m38.4.csv

  ##Data file describing snord116 locations
  ##Needed to generate the imprinted genes list
  snord116.file:  imprinted_genes_list/snord116_ensembl_m38.4.csv

  snord:  b6_reference/mus_musculus.GRCm38.75/snord
  ##Data file describing all imprinted genes, collated together from multiple sources
  imprintedGenesFile: imprinted_genes_list/feb2014.archive.ensembl.org_allImprintedGenes.csv

  ##data file describing all transcripts of all genes in the regions covered by the imprintedGenesFile genes
  imprintedTranscriptsFile: imprinted_genes_list/imprinted_transcripts.txt

  ##Should we rebuild the imprintedGenesFile? 
  rebuildImprinted: no

  ##folder containing GBRS reference informatio
  GBRS.data: gbrs

  ##The transibtion probability file to be used. AT present, DO, 1gen outbreeding, female
  GBRS.tranprob: tranprob.DO.G1.F.npz




##properties related to construction of the variant db
variantdb:
  dbfolder: ../output/isvdb

  ##properties describing construction of the "full" db, i.e. everything
  full:
    ##name of the database
    name: full_1410
    ##should we rebuild the VCF file corresponding to the databasel i.e. should we apply vcftools
    ## to filter our irrelevant strains and/or regions? Intended to speed testing, leave to yes in real db generation
    rebuildVCF: yes
    ##Should we rebuild the founder variant haplotypes, or can we assume it is already built. Intended to speed testing, leave to yes in real db generation
    rebuildFounder: yes
    ##Should we rebuild the information for all CC strains? This is the really computationally expensive part. Intended to speed testing, leave to yes in real db generation
    rebuildCC: yes

  ##properties describing construction of the exon database
  exon:
    name: exon_1410
    rebuildVCF: yes
    rebuildFounder: yes
    rebuildCC: yes
    padding: 100

  ## any probability in the cc probability tables that is less than this probability is discarded;
  ## i.e. if the probability of diplotype being CC, is .005, it is disregarded and isn't stored in the database.
  truncate_cc_prob: 0.01

  ## max number of variants of each type (indel, snp) that the vcf parsing will bother storing. Meant for testing. .na means build them all.
  var_limit: 20 #.na #20
 
  ##max number of cc lines that variant db will bother storing. Meant for testing. .na means build all.
  cc_limit: .na

  ##The chromosomes that will be built. .na means build them all
  chr_range: .na


