external:
  kallisto: kallisto
  bowtie: bowtie
  #bam.to.emase: /nas/depts/006/valdar-lab/users/doreper/emase/scripts/bam-to-emase
  bam.to.emase: bam-to-emase
  combine.emase.files: combine-emase-files
  run.emase: run-emase
  gbrs: gbrs

output: ../output
tmpdir: ../output/tmp
onCluster: yes

mnp:
  mc.cores: 5 #1 #5
  limit: .na
  SSVA.numperm: 400 #400 #20	

  evalprobelimit: .na
  recomputeProbeInfo: no
  output: ../outkill


##  uselme: yes	
##  computeBehaviorCor: no

ovx:
  numPerm: 1000
  numImp: 500
  iter: 20000
  mc.cores: 1        
  rebuildData: yes
  normalizeBeforeTransform: no
  normalizeAfterTransform: no